version: 2.1

  


jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - run: | 
         echo "Running  the scanning ..."   
         if [[ $CIRCLE_TAG =~ ^prod|preprod$ ]]; then  
            sh sonar_run.sh 
         fi;

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud